---
- hosts: digitalocean

  vars:
    ansible_python_interpreter: /usr/bin/python3
    server_name: toursbyepic.com
    symfony_root_dir: /var/www/toursbyepic
    symfony_web_dir: "{{ symfony_root_dir }}/public"
    symfony_console_path: "{{ symfony_root_dir }}/bin/console"

  tasks:
    - ping: ~

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      become: true
      apt:
        upgrade: safe

    - name: Install low-level utilities
      become: true
      apt:
        name:
          - zip
          - unzip

    - name: Install Git VCS
      become: true
      apt:
        name: git
        state: latest

    - name: Install Nginx web server
      become: true
      apt:
        name: nginx
        state: latest
      notify: Restart Nginx

    - name: Add Symfony config template to the Nginx available sites
      become: true
      template:
        src: templates/symfony.conf
        dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
      notify: Restart Nginx

    - name: Enable Symfony config template from Nginx available sites
      become: true
      file:
        src: "/etc/nginx/sites-available/{{ server_name }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
        state: link
      notify: Restart Nginx

    - name: Add enabled Nginx site to /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "165.22.80.233 {{ server_name }}"

    - name: Install MySQL DB server
      become: true
      apt:
        name: mysql-server
        state: latest

    - name: Create database user with name with all database privileges
      mysql_user:
        name: kibolabs
        password: "intelcorei5"
        priv: '*.*:ALL'
        state: present

    - name: Add PHP 7 PPA repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP packages
      become: true
      apt:
        name:
        - php7.4-cli
        - php7.4-curl
        - php7.4-fpm
        - php7.4-intl
        - php7.4-mysql
        - php7.4-xml
        state: latest
      notify: Restart PHP-FPM

    - name: Create project directory and set its permissions
      become: true
      file:
        path: "{{ symfony_root_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Checkout Git repository
      git:
        repo: https://github.com/wamkelekile/toursbyepic.git
        dest: "{{ symfony_root_dir }}"
        force: yes

    - name: Download Composer
      script: scripts/install_composer.sh

    - name: Move Composer globally
      become: true
      command: mv composer.phar /usr/local/bin/composer

    - name: Set permissions on Composer
      become: true
      file:
        path: /usr/local/bin/composer
        mode: "a+x"

    - name: Install Composer's dependencies
      composer:
        working_dir: "{{ symfony_root_dir }}"
        no_dev: no

    # Symfony console commands
    - name: Create DB if not exists
      command: '{{ symfony_console_path }} doctrine:database:create --if-not-exists'

    - name: Execute migrations
      command: '{{ symfony_console_path }} doctrine:migrations:migrate --no-interaction'

  handlers:
    - name: Restart Nginx
      become: true
      service:
        name: nginx
        state: restarted

    - name: Restart PHP-FPM
      become: true
      service:
        name: php7.4-fpm
        state: restarted